name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macOs-latest
            BOOST_ROOT: /usr/local/opt/openssl@1.1

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - name: Install submodules
      run: |
        git submodule init
        git submodule update
        
    - run: ls
      if: ${{matrix.os == 'windows-latest'}}
      working-directory: 'C:/Program Files'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBOOST_ROOT_DIR=${{matrix.BOOST_ROOT}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
