name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macOs-latest
            OPENSSL_ROOT: /usr/local/opt/openssl@1.1

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - name: Install submodules
      run: |
        git submodule init
        git submodule update
      
    - name: Install OpenSSL Windows
      run: choco install openssl
      if: ${{matrix.os == 'windows-latest'}}

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        OPENSSL_ROOT_DIR: ${{matrix.OPENSSL_ROOT}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
